# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "google-review-app-prod"
client_id = "a0ada2d4edb9cb42318728c85ee96733"
application_url = "https://google-review-app.gadget.app/api/shopify/install-or-render"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://google-review-app.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "google-review-import-store.myshopify.com"
